# Deploy the private registry stack
deploy:
	docker stack deploy --compose-file docker-compose.yml registry

# List the tasks in the registry stack
ps:
	docker stack ps registry

# List the services in the registry stack
services:
	docker stack services registry

# Remove the registry stack
rm:
	docker stack rm registry
