# Deploy the private registry stack
deploy:
	docker stack deploy --compose-file docker-compose.yml registry

# Remove the registry stack
down:
	docker stack rm registry

# List the tasks in the registry stack
ps:
	docker stack ps registry
