# Run containers
up:
	docker-compose up -d

# Stop containers
down:
	docker-compose down --remove-orphans

# Build containers
build:
	docker-compose build

# Build and run containers
build-up:
	docker-compose up -d --build --force-recreate
