# Start containers
up:
	docker-compose up -d

# Stop containers
down:
	docker-compose down --remove-orphans

# Build containers
build:
	docker-compose build

# Build and restart containers
update: build up
