#!/bin/bash

INSTALL_BREEZE=false
ENV_DIST_FILE=.env.dev
ENV_FILE=.env
GATEWAY_NETWORK=gateway
COMPOSE_FILE=docker-compose.dev.yml
APP_CONTAINER=app
TEMP_INSTALL_DIRECTORY=src
SELF_DESTRUCTION=false

install_laravel() {
  # Init a new Laravel app into a temporary directory
  docker compose -f "$COMPOSE_FILE" run --rm --no-deps "$APP_CONTAINER" \
    composer create-project --prefer-dist laravel/laravel "$TEMP_INSTALL_DIRECTORY"

  # Set ownership of the temporary directory to the current user
  sudo chown -R "$(id -u)":"$(id -g)" ./${TEMP_INSTALL_DIRECTORY}

  # Remove the default file with environment variables
  rm ${TEMP_INSTALL_DIRECTORY}/${ENV_FILE}

  # Move everything from the temporary directory to the current directory
  mv ${TEMP_INSTALL_DIRECTORY}/* ${TEMP_INSTALL_DIRECTORY}/.* .

  # Remove the temporary directory
  rm -r ${TEMP_INSTALL_DIRECTORY}

  # Generate the application key
  docker compose -f "$COMPOSE_FILE" run --rm --no-deps "$APP_CONTAINER" \
    php artisan key:generate --ansi
}

install_octane() {
  # Install the Octane package
  docker compose -f "$COMPOSE_FILE" run --rm --no-deps "$APP_CONTAINER" \
    composer require laravel/octane

  # Configure the Octane package
  docker compose -f "$COMPOSE_FILE" run --rm --no-deps \
    --user "$(id -u)":"$(id -g)" "$APP_CONTAINER" \
    php artisan octane:install --server=swoole
}

install_breeze() {
    # Install the Breeze package
    docker compose -f "$COMPOSE_FILE" run --rm --no-deps "$APP_CONTAINER" \
      composer require laravel/breeze --dev

    # Configure the Breeze package
    docker compose -f "$COMPOSE_FILE" run --rm --no-deps \
      --user "$(id -u)":"$(id -g)" "$APP_CONTAINER" \
      php artisan breeze:install api
}

# Determine the Nuxt version
if [ "$1" == "--breeze" ]; then
    shift 1
    INSTALL_BREEZE=true
fi

# Configure self destruction
if [ "$1" == "--destruct" ]; then
    shift 1
    SELF_DESTRUCTION=true
fi

# Copy the .env file from the dist
if [ ! -f "$ENV_FILE" ]; then
    cp "$ENV_DIST_FILE" "$ENV_FILE"
fi

# Create a shared gateway network
docker network create "$GATEWAY_NETWORK"

# Build containers
make build.all

# Install the Laravel framework
install_laravel

# Install the Octane package
install_octane

# Install the Breeze package
if [ "$INSTALL_BREEZE" == true ]; then
    install_breeze
fi

# Start containers
docker compose -f "$COMPOSE_FILE" up -d

# Delete installation files
if [ "$SELF_DESTRUCTION" == true ]; then
    echo "Removing stubs directory"
    rm -rf stubs

    echo "Removing installation script"
    rm ./install
fi

# Print the final message
echo "The API app has been installed and run on http://localhost:8000."
